# Generated by Django 6.0.2 on 2026-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='last_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
