# Generated by Django 6.0.2 on 2026-02-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionrisk',
            old_name='source',
            new_name='score',
        ),
    ]
