# Generated by Django 6.0.2 on 2026-04-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='account_type',
            new_name='category_type',
        ),
    ]
