# Generated by Django 6.0.2 on 2026-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_account_type_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Bank'), ('CREDIT', 'Credit')], max_length=10),
        ),
    ]
